blank_issues_enabled: false
contact_links:
  - name: Some issue with your console after/during following the guide?
    url: https://discord.gg/6ryxnkS
    about: "Please join the Wii mini Hacking Discord server to for support-related questions"
